### ISSUE TITLE
Will this work for WAN access as well?

### ISSUE THREAD

**Issue by ambroselittle** [j-c-m/ubnt-letsencrypt#5]
Looks great. Thanks for doing it. I plan to try it later or tomorrow for LAN. Do you foresee any issues doing the same for WAN access? I assume I can just swap in the external public IP address?

**Comment by j-c-m** [comment]
I think it should work.  I would first try adding the WAN  IP in step 1, resulting in 2 entries total. 

I wouldn't recommend opening the administration GUI on the WAN side unless absolutely necessary due to the security implications, and then I would limit access via firewall, your requirements may vary.

**Comment by ambroselittle** [comment]
Awesome! Worked like a charm in both LAN and WAN using my domain. This is just a home router, and occasionally I do need to access it remotely. Thanks a bunch!
